/-
Copyright (c) 2026 Guy Fischman. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Guy Fischman
-/

/-!
# The challenge: induction on ℕ, in Mathlib's words

`Nat` and its literals are Lean core's. `Nat.rec`, `Nat.rec_aux`, `induction`
and `Nat.strongRecOn` are not named, and the Solution may not close this by
`induction` --- which would discharge it from the inductive's own eliminator and
use nothing else.

## Which statement, and why it is the right one to ask for

This is the row `the Peano axioms`. Mathlib gets induction for free: `Nat` is an
inductive type, so `Nat.rec` is generated by the kernel and the principle is a
constructor fact with nothing to prove.

The tower has no primitive `Nat`. It has `omega`, built from `empty` and `succ`
by infinity + separation, and the induction principle is the `induct` field of
`SetTheory.IsPeano` --- which quantifies over every subset of the carrier, making
it second-order. `SetTheory.omega_isPeano` is the theorem that `omega` with
`empty` and `graphOn omega omega succ` satisfies all seven clauses, and its
`induct` is what this challenge is discharged from.

So the comparison is the same shape as the `PairEncoding` row and worth making
for the same reason: mathlib assumes what the tower proves, and the pair checks
that the two are the same principle.

## The subset/predicate gap is the content of the transfer

The tower's `induct` speaks of a set `S ⊆ omega`; this challenge speaks of a
Lean predicate `S : Nat → Prop`. Those are not the same thing, and bridging them
is exactly `sep` --- separation turns the predicate into a subset. That step is
the reason this is a real pair and not a rename.
-/

namespace Comparator.PeanoInduction

/-- The challenge. Induction on `Nat`, as a second-order principle over an
arbitrary predicate.

`Solution.lean` must close this using the `FromAxioms` tower. Nothing in this
file may be changed to make that easier. -/
def challenge : Prop :=
  ∀ S : Nat → Prop, S 0 → (∀ n, S n → S (n + 1)) → ∀ n, S n

/-- The challenge is not vacuous, and Lean core itself is the witness ---
here by the eliminator the Solution is forbidden to use.

A `Prop` nobody has shown inhabited says nothing --- and a draft of the
`Adjunction` challenge factored its equation into a helper returning `True`,
which would have made that whole pair vacuous while still compiling. That is the
failure this theorem exists to exclude. -/
theorem challenge_is_mathlibs : challenge := by
  intro S h0 hs n
  induction n with
  | zero => exact h0
  | succ k ih => exact hs k ih

end Comparator.PeanoInduction
