#!/usr/bin/env python3
"""The library as a dependency DAG, from the axioms upward.

    python3 tools/dag.py            # what would change
    python3 tools/dag.py --record   # write figures/dag.html
    python3 tools/dag.py --check    # CI: fail if stale or unparseable

The five SVGs answer questions about the *registry*. This answers the one
about the *library*: what is built on what, starting from the axioms Lean's
kernel assumes, with each further axiom entering only where it is first
needed.

**"First needed" is not a metaphor here.** A declaration's axioms are the
union of its dependencies' axioms plus whatever its own proof adds, so a
declaration *introduces* an axiom exactly when it uses one that none of its
dependencies use. 341 of 6196 declarations introduce anything at all, and
only **nine** introduce `Classical.choice` -- so the classical fragment is
not a region of the graph, it is nine entry points and their reachable set,
which turns out to reach almost nothing.

**Why HTML and not another SVG.** The graph has 6196 nodes and 75217 edges.
A static image of that is a smear, and the questions worth asking of it --
what does this rest on, what breaks if this is wrong, where does `choice`
first appear -- are all *navigation*. So this emits a self-contained page:
layered layout computed here, drawn on a canvas, with pan, zoom, search, a
lemma toggle, and click-to-trace back to the axioms.

The layering is a longest path from a root, so a node sits above everything
it depends on and adding an edge moves the picture rather than requiring it
to be redrawn -- the same rule the lattice figure uses.
"""

import argparse
import html
import json
import pathlib
import re
import sys
import xml.dom.minidom     # noqa: F401  (kept for symmetry with figures.py)

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "figures" / "dag.html"

GENERATES = {"path": "figures/dag.html", "check": ["--check"]}

MARKER = "<!-- generated by `python3 tools/dag.py` -->"

# The kernel's own assumptions. Everything else in the library is a theorem.
KERNEL = ("propext", "Quot.sound", "Classical.choice")

REPO = "https://github.com/guyfischman/FromAxioms/"
_SOURCES = {}


def _decl_url(by, name):
    """The published source line declaring `name`, as a link."""
    r = by.get(name)
    if r is None:
        return None
    rel = r["module"].replace(".", "/") + ".lean"
    if rel not in _SOURCES:
        f = ROOT / rel
        _SOURCES[rel] = f.read_text(errors="replace") if f.exists() else None
    text = _SOURCES[rel]
    if text is None:
        return None
    short = name.split(".")[-1]
    m = re.search(
        r"^[ \t]*(?:@\[[^\]]*\][ \t]*)*"
        r"(?:(?:private|protected|noncomputable|partial|unsafe)[ \t]+)*"
        r"(?:theorem|lemma|def|abbrev|structure|class|inductive|instance|axiom|opaque)"
        r"[ \t]+(?:[\w.]*\.)?" + re.escape(short) + r"(?![\w'.])",
        text, re.M)
    line = f"#L{text.count(chr(10), 0, m.start()) + 1}" if m else ""
    return f"{REPO}blob/master/{rel}{line}"


def _core_url(name):
    """`name` in Lean core, at the toolchain's own commit."""
    import subprocess
    try:
        prefix = subprocess.run(["lean", "--print-prefix"], capture_output=True,
                                text=True, cwd=ROOT).stdout.strip()
        version = subprocess.run(["lean", "--version"], capture_output=True,
                                 text=True, cwd=ROOT).stdout
    except OSError:
        return None
    commit = re.search(r"commit ([0-9a-f]{40})", version)
    src = pathlib.Path(prefix) / "src" / "lean"
    if not commit or not src.is_dir():
        return None
    ns, _, short = name.rpartition(".")
    pat = re.compile(r"^[ \t]*(?:theorem|lemma|def|abbrev)[ \t]+"
                     r"(?:" + re.escape(name) + "|" + re.escape(short) + r")(?![\w'.])",
                     re.M)
    for f in sorted((src / "Init").rglob("*.lean")):
        text = f.read_text(errors="replace")
        m = pat.search(text)
        if m and (not ns or f"namespace {ns}" in text or name in m.group(0)):
            line = text.count("\n", 0, m.start()) + 1
            rel = f.relative_to(src).as_posix()
            return (f"https://github.com/leanprover/lean4/blob/{commit.group(1)}"
                    f"/src/{rel}#L{line}")
    return None


def _pairs():
    """Comparator pairs keyed by the landmark rows they match.

    Mathlib links are pinned to the revision `comparator/lake-manifest.json`
    records, and use the `path:line` each pair gives for its statement, so an
    upstream change cannot move what a link points at.
    """
    y = ROOT / "comparator" / "formalization.yaml"
    if not y.exists():
        return {}
    rev = None
    man = ROOT / "comparator" / "lake-manifest.json"
    if man.exists():
        for pkg in json.loads(man.read_text()).get("packages", []):
            if pkg.get("name") == "mathlib":
                rev = pkg.get("rev")
    lines = y.read_text().split("\n")
    starts = [i for i, l in enumerate(lines) if l.startswith("  - id: ")]
    out = {}
    for k, s in enumerate(starts):
        e = starts[k + 1] if k + 1 < len(starts) else len(lines)
        while e > s and not lines[e - 1].strip():
            e -= 1
        blk = "\n".join(lines[s:e])

        def get(key):
            m = re.search(r"^    " + key + r":[ \t]*(.+)$", blk, re.M)
            return m.group(1).strip() if m else None

        pid = lines[s][len("  - id: "):].strip()
        ml, src = get("mathlib"), get("mathlib_source") or ""
        mlu = None
        m = re.match(r"(Mathlib/\S+\.lean):(\d+)$", src)
        if ml and ml.startswith("none"):
            ml = None
        elif m and rev:
            mlu = (f"https://github.com/leanprover-community/mathlib4/blob/"
                   f"{rev}/{m.group(1)}#L{m.group(2)}")
        elif ml and "Lean core" in src:
            mlu = _core_url(ml)
        d = "".join(w[:1].upper() + w[1:] for w in pid.split("-"))
        pair_dir = ROOT / "comparator" / "Comparator" / d
        rec = {"id": pid, "ml": ml, "mlu": mlu,
               "src": "Lean core" if "Lean core" in src else "Mathlib",
               "dir": (f"{REPO}tree/master/comparator/Comparator/{d}"
                       if pair_dir.is_dir() else None),
               "yaml": f"{REPO}blob/master/comparator/formalization.yaml"
                       f"#L{s + 1}-L{e}"}
        for row in re.findall(r'^      - "(.+)"$', blk, re.M):
            out[row] = rec
    return out


def graph():
    """Nodes, edges, layers, and where each axiom first enters."""
    sys.path.insert(0, str(ROOT / "tools"))
    import astexport
    rows = astexport.export(cached_only=True)
    if rows is None:
        return None

    by = {r["name"]: r for r in rows}
    # `d in by` discards any reference the export does not carry. On a
    # complete export that is 0 of 75,470 edges, so the filter looks inert --
    # but a partial export reaches it: with 5% of rows absent it silently
    # drops 2,733 references and simply draws a smaller graph. Nothing else
    # can catch that, because `figclaims.py` recomputes the totals from this
    # same export, so both numbers move together and agree.
    dropped = sum(1 for n, r in by.items()
                  for d in r.get("refs", ()) if d != n and d not in by)
    deps = {n: sorted({d for d in r.get("refs", ()) if d in by and d != n})
            for n, r in by.items()}

    if dropped:
        print(f"  WARNING -- {dropped} reference(s) point at declarations the "
              f"export does not carry; the graph is drawn without them and "
              f"its edge count is an undercount. The export is partial: "
              f"refresh it before reading the picture.")

    # A declaration introduces an axiom when none of its dependencies use it.
    intro = {}
    for n, r in by.items():
        used = set()
        for d in deps[n]:
            used |= set(by[d].get("axioms", ()))
        got = sorted(set(r.get("axioms", ())) - used)
        if got:
            intro[n] = got

    # Longest path from a root. Iterative, since the graph is 6k deep in the
    # worst case and Python's recursion limit is not.
    layer = {n: 0 for n in by}
    for n in _topo(by, deps):
        for d in deps[n]:
            if layer[d] + 1 > layer[n]:
                layer[n] = layer[d] + 1

    names = sorted(by)
    idx = {n: i for i, n in enumerate(names)}
    # The axioms are roots of the picture, not properties of it. Each gets a
    # node at layer -1 and an edge to every declaration that *introduces* it,
    # which is what makes the drawing start where the user's question does:
    # at the kernel's assumptions, with each entering only where first needed.
    # Index order must match the order the root nodes are APPENDED below, not
    # KERNEL's declaration order -- `Classical.choice` is appended last so it
    # sits at the bottom of the rail, and an index computed from KERNEL would
    # point every choice edge at a principle instead.
    ax_idx = {"propext": len(names), "Quot.sound": len(names) + 1}

    # The kernel axioms are not the whole cost structure, and on their own
    # they are the least interesting part of it: `Classical.choice` is what
    # Lean assumes, while `LLPO`, `FAN`, `DC`, `EM` and the rest are what the
    # *mathematics* costs. Those are `Prop` hypotheses rather than axioms, so
    # `#print axioms` cannot see them -- but the elaborated `refs` graph can,
    # because a theorem taking `(h : LLPO)` mentions `LLPO` in its type.
    #
    # So each principle the lattice names, and which is defined here, becomes
    # a root beside the axioms, with an edge to every declaration that names
    # it. That is the minimal-principle reading: what a theorem needs, not
    # merely what the kernel assumed underneath it.
    lat = json.loads((ROOT / "tools" / "lattice.json").read_text())
    want = {n.lower() for n in lat["nodes"]} | {"fan", "wkl", "pathselection"}
    # A STATEMENT PRICED AS A LANDMARK IS A RESULT, NOT A PRINCIPLE. The lattice
    # carries `ExactIVT01` as a node so its place can be computed; on the rail
    # it would read as something other theorems pay for.
    equivs = json.loads((ROOT / "tools" / "classical.json").read_text()) \
        .get("_equivalences", [])
    priced = {e["statement"] for e in equivs if e.get("landmark")}
    cand = {}
    for n in names:
        s = n.split(".")[-1]
        if s.lower() in want and n not in priced:
            cand.setdefault(s.lower(), []).append(n)
    princ = {}
    for key, opts in cand.items():
        # Prefer the one declared in `Omniscience.lean`, then the shallowest
        # name: the principles live there, and a collision like `D0.mp` does
        # not.
        best = sorted(opts, key=lambda n: (
            by[n]["module"].split(".")[-1] != "Omniscience",
            n.count("."), n))[0]
        princ[best.split(".")[-1]] = best
    # A PRINCIPLE NOTHING DEPENDS ON IS NOT DRAWN. The lattice names more
    # principles than any one cut uses, and each was given a root on the rail
    # whether or not a single declaration took it as a hypothesis -- so the
    # picture showed a cost that nothing here pays. A root is where an edge
    # starts; without one it says nothing about this library, and a reader
    # reasonably takes a drawn principle as one something needs.
    users = {s: [n for n in names if full in by[n].get("refs", ()) and n != full]
             for s, full in princ.items()}
    princ = {s: full for s, full in princ.items() if users[s]}
    # STRENGTH ORDER, derived from the lattice's own closure rather than
    # listed by hand. A principle that derives more is stronger; ties keep the
    # alphabetical order so the layout is stable across runs. The kernel
    # axioms bracket it: `propext` and `Quot.sound` are the two Lean assumes
    # without any choice content, and `Classical.choice` is the strongest
    # assumption in the picture -- it proves `em` and `funext`, which neither
    # of the others does. So the rail reads weakest at the top to strongest at
    # the bottom, and an edge's colour is the strongest thing flowing down it.
    edges_l = lat["edges"]

    def _derives(start):
        have, changed = {start}, True
        while changed:
            changed = False
            for e in edges_l:
                pre = e["from"] if isinstance(e["from"], list) else [e["from"]]
                if all(x in have for x in pre) and e["to"] not in have:
                    have.add(e["to"])
                    changed = True
        return have - {start}

    strength = {s: len(_derives(s.lower())) for s in princ}
    ranked = sorted(princ, key=lambda s: (strength[s], s))
    pr_idx = {s: len(names) + 2 + i for i, s in enumerate(ranked)}
    ax_idx["Classical.choice"] = len(names) + 2 + len(ranked)
    nodes = [{
        "n": n.split(".")[-1],
        "f": n,
        "m": by[n]["module"].split(".")[-1],
        "k": by[n]["kind"],
        "l": layer[n],
        "a": [a for a in KERNEL if a in by[n].get("axioms", ())],
        # The PRINCIPLES the statement takes, read off its type. The panel
        # listed kernel axioms alone, so `mvt_lagrange_of_llpo_binaryDC_dc` --
        # whose own name says what it takes -- reported `propext, Quot.sound`
        # and nothing else, while the drawing showed its edges to LLPO,
        # BinaryDC and DC. The edges were right and the panel was incomplete,
        # which is the worse way round: a reader checks the panel.
        "p": sorted({x.split(".")[-1] for x in by[n].get("typeRefs", ())}
                    & set(princ)),
        "i": intro.get(n, []),
        "d": len(deps[n]),
    } for n in names]
    # Landmarks, so the dated results are findable rather than being three
    # of six thousand identical dots.
    sys.path.insert(0, str(ROOT / "tools"))
    # ONE node per dated landmark, not every declaration whose name happens to
    # match a detector. The detectors are regexes over squashed names, so a row
    # like "the mean value theorem" matched dozens of lemmas and the
    # landmarks-only view showed 422 dots named `rec`, `smulFun`, `HasDerivAt`
    # -- declaration names, when what a reader wants is "irrationality of √2".
    #
    # The representative is the most DEPENDED-UPON match: a landmark's headline
    # theorem is the one the rest of the library builds on, and ties break on
    # the shorter name, which is the general statement rather than a variant.
    land = {}
    # THE PUBLISHED LANDMARKS, read from `tools/landmarks.json`.
    #
    # This imported the dating table, which is a research instrument and not
    # part of this tree, inside a `try` that fell back to marking nothing. So
    # the first published graph opened on `only landmarks` over an empty
    # canvas: the failure mode of a missing input that is caught and ignored.
    # Absence is now refused, because a graph with no landmark in it is not a
    # smaller answer to the question a reader came with, it is no answer.
    marks = ROOT / "tools" / "landmarks.json"
    if not marks.exists():
        raise SystemExit(f"missing {marks} -- which landmark a declaration "
                         f"carries is not recoverable from the source alone")
    # ONE NODE PER ROW. A row reached by two witnesses keeps a theorem where
    # there is one, then the more depended-upon.
    rdeg = {}
    for n in names:
        for d in deps[n]:
            rdeg[d] = rdeg.get(d, 0) + 1
    best = {}
    for name, (what, yr) in json.loads(marks.read_text()).items():
        if name not in by:
            continue
        # A theorem before a definition: `sqrtTwoP` is used far more than
        # `sq_two_irrational`, and is the proposition rather than its proof.
        key = (by[name]["kind"] == "theorem", rdeg.get(name, 0), -len(name), name)
        if what not in best or key > best[what][0]:
            best[what] = (key, name, yr)
    land = {name: (what, yr) for what, (_k, name, yr) in best.items()}
    if not land:
        raise SystemExit(f"{marks} names no declaration this tree has")
    # THE BRACKET: what a reversal proves the landmark needs, and what the
    # library's proof of it uses. Only published proofs are cited, so a side
    # with nothing published says so rather than naming a declaration the
    # reader cannot open.
    full_of = {full: s for s, full in princ.items()}
    by_key = {s.lower(): s for s in princ}

    def principles_in(start):
        seen, stack = {start}, [start]
        while stack:
            for d in deps[stack.pop()]:
                if d not in seen:
                    seen.add(d)
                    stack.append(d)
        return sorted({full_of[r] for x in seen for r in by[x].get("refs", ())
                       if r in full_of and r != x})

    def link(s):
        return {"p": s, "pu": _decl_url(by, princ[s])}

    pairs = _pairs()
    for nd in nodes:
        got = land.get(nd["f"])
        # `the` dropped from the front, so an alphabetical list sorts by the
        # result's own name.
        nd["lm"] = (re.sub(r"^the\s+", "", got[0]) + f" ({got[1]})") if got else ""
        nd["yr"] = got[1] if got else None
        if not got:
            continue
        name = nd["f"]
        nd["u"] = _decl_url(by, name)
        entry = next((e for e in equivs
                      if name in (e["statement"], e.get("reversal"), e.get("forward"))),
                     None)
        rev, via, used = [], name, None
        if entry:
            s = by_key.get(entry["principle"].lower())
            if s and entry.get("reversal") in by:
                rev.append({**link(s), "by": entry["reversal"],
                            "bu": _decl_url(by, entry["reversal"])})
            # The forward proof is what USES principles. With it unpublished
            # there is no proof here to read them off, and the statement's own
            # cone would report `none` for a result that needs one.
            via = entry.get("forward") if entry.get("forward") in by else None
            if via:
                used = [link(s) for s in principles_in(via)]
                # Hypotheses the lattice does not draw as principles, which the
                # registry records beside the proof.
                for x in entry.get("extra", []):
                    full = next((n for n in by if n.split(".")[-1] == x), None)
                    if full and x not in {u["p"] for u in used}:
                        used.append({"p": x, "pu": _decl_url(by, full)})
        else:
            used = [link(s) for s in principles_in(name)]
        nd["br"] = {"rev": rev, "used": used, "via": via,
                    "vu": _decl_url(by, via) if via else None}
        if got[0] in pairs:
            nd["pr"] = pairs[got[0]]

    # `r` is the rail rank: weakest at 0. `propext` and `Quot.sound` sit above
    # every principle because Lean assumes them with no choice content;
    # `Classical.choice` sits below every one because it proves `em`, which is
    # the top of the lattice. The principles fill the middle in derived order.
    nodes.append({"n": "propext", "f": "propext", "m": "(kernel axiom)",
                  "k": "axiom", "l": -1, "a": ["propext"], "i": [], "d": 0,
                  "lm": "", "r": 0})
    nodes.append({"n": "Quot.sound", "f": "Quot.sound", "m": "(kernel axiom)",
                  "k": "axiom", "l": -1, "a": ["Quot.sound"], "i": [], "d": 0,
                  "lm": "", "r": 0})
    for i, s in enumerate(ranked):
        nodes.append({"n": s, "f": princ[s], "m": "(principle)",
                      "k": "principle", "l": -1, "a": [], "i": [], "d": 0,
                      "lm": "", "r": i + 1, "u": _decl_url(by, princ[s])})
    nodes.append({"n": "Classical.choice", "f": "Classical.choice",
                  "m": "(kernel axiom)", "k": "axiom", "l": -1,
                  "a": ["Classical.choice"], "i": [], "d": 0, "lm": "",
                  "r": len(ranked) + 1})
    edges = [[idx[d], idx[n]] for n in names for d in deps[n]]
    edges += [[ax_idx[a], idx[n]] for n, got in intro.items() for a in got]
    edges += [[pr_idx[s], idx[n]] for s, full in princ.items()
              for n in names if full in by[n].get("refs", ()) and n != full]
    return {"nodes": nodes, "edges": edges}


def _topo(by, deps):
    """Dependency order, iteratively. Cycles cannot occur in a Lean env."""
    seen, out = set(), []
    for start in by:
        if start in seen:
            continue
        stack = [(start, False)]
        while stack:
            n, done = stack.pop()
            if done:
                out.append(n)
                continue
            if n in seen:
                continue
            seen.add(n)
            stack.append((n, True))
            for d in deps[n]:
                if d not in seen:
                    stack.append((d, False))
    return out


PAGE = """%(marker)s
<!doctype html>
<meta charset="utf-8">
<title>FromAxioms -- the library from the axioms up</title>
<style>
 :root { --ink:#0f172a; --muted:#475569; --line:#cbd5e1; --bg:#ffffff;
         --blue:#1d4ed8; --red:#b91c1c; --amber:#b45309; }
 @media (prefers-color-scheme: dark) {
   :root { --ink:#f1f5f9; --muted:#94a3b8; --line:#334155; --bg:#0b1220; } }
 html,body { margin:0; height:100%%; background:var(--bg); color:var(--ink);
   font:13px/1.5 ui-sans-serif, system-ui, sans-serif; }
 #bar { position:fixed; top:0; left:0; right:0; padding:8px 12px;
   background:var(--bg); border-bottom:1px solid var(--line); z-index:2;
   display:flex; gap:14px; align-items:center; flex-wrap:wrap; }
 #bar b { font-weight:600 } label { user-select:none; cursor:pointer }
 input[type=search] { padding:3px 7px; border:1px solid var(--line);
   border-radius:4px; background:var(--bg); color:var(--ink); width:190px }
 canvas { display:block; cursor:grab } canvas.drag { cursor:grabbing }
 #side { position:fixed; right:0; top:41px; bottom:0; width:330px;
   overflow:auto; padding:12px; border-left:1px solid var(--line);
   background:var(--bg); font-size:12px }
 #side h3 { margin:0 0 6px; font-size:13px } .p { color:var(--muted) }
 .tag { display:inline-block; padding:1px 6px; border-radius:9px;
   font-size:11px; font-weight:600; color:#fff; margin-right:4px }
 code { font-size:11px }
 #side a { color:var(--blue) }
 #side ul.lms { padding-left:16px; margin:4px 0 }
 #side .sec { margin:10px 0 2px; font-weight:600 }
 #side .row { margin:3px 0 }
</style>
<div id="bar">
  <b>FromAxioms</b>
  <span class="p">%(count)d declarations, %(edges)d dependencies</span>
  <label><input type=checkbox id=lemmas> lemmas (%(lemmas)d)</label>
  <label><input type=checkbox id=onlyax> only axiom-introducers (%(intro)d)</label>
  <label><input type=checkbox id=classical> highlight classical</label>
  <label><input type=checkbox id=alledges> all %(edges)d edges</label>
  <label><input type=checkbox id=onlylm checked> only landmarks (%(land)d)</label>
  <input type=search id=q placeholder="search a declaration">
  <span class="p" id=status></span>
</div>
<canvas id=c></canvas>
<div id=side><h3>Click a node</h3><div class=p>Its dependencies, its axioms,
and where each axiom first entered the library beneath it.</div></div>
<script>
const DATA = %(data)s;
const N = DATA.nodes, E = DATA.edges;
N.forEach((n,i)=>{ n.id=i; n.up=[]; n.dn=[]; });
E.forEach(([a,b])=>{ N[b].up.push(a); N[a].dn.push(b); });
N.forEach(n => n.leaf = (n.k==='theorem' && n.dn.length===0));

const MODS=[...new Set(N.map(n=>n.m))].sort();
const HUE={}; MODS.forEach((m,i)=>HUE[m]=Math.round(360*i/MODS.length));
const byL = {}; N.forEach(n=>(byL[n.l]=byL[n.l]||[]).push(n));
Object.values(byL).forEach(col => col.sort((a,b)=>
  a.m===b.m ? a.n.localeCompare(b.n) : a.m.localeCompare(b.m)));
const COLW=30, ROWH=13;
Object.entries(byL).forEach(([l,col]) =>
  col.forEach((n,i)=>{ n.x = 130 + (+l)*COLW; n.y = 70 + i*ROWH; }));
// The axioms are the picture's roots: one column, far left, well separated.
// One rail, ordered by STRENGTH rather than by kind: propext and Quot.sound at
// the top (Lean assumes them with no choice content), the principles in the
// order the lattice's own closure puts them, and Classical.choice at the bottom
// because it proves em, which is the top of the lattice. Reading down the rail
// is reading up in strength, which is the picture's actual claim.
const RAIL = N.filter(n=>n.k==='axiom'||n.k==='principle')
              .sort((a,b)=>a.r-b.r);
RAIL.forEach((n,i)=>{ n.x=40; n.y=120+i*44; });
const RMAX = Math.max(1, ...RAIL.map(n=>n.r));
// A spectrum, not four fixed colours: each strength gets its own hue, and two
// principles the lattice cannot separate share one. Blue is cheap, red is
// Classical.choice -- the same reading as everywhere else in the project.
function railHue(r){ return 210 - 210*(r/RMAX); }
function railCol(n){ return 'hsl(' + railHue(n.r) + ' 62%% 45%%)'; }
// What is the STRONGEST root reaching each declaration. Computed once: an
// edge's colour is the strongest assumption flowing down it, so a reader can
// see the price of a region without selecting anything.
const STRONG = new Array(N.length).fill(-1);
(function(){
  const down = N.map(()=>[]);
  for(const [a,b] of E) down[a].push(b);
  for(const root of RAIL){
    const i = N.indexOf(root), seen = new Uint8Array(N.length), st = [i];
    while(st.length){ const j = st.pop();
      if(seen[j]) continue; seen[j] = 1;
      if(root.r > STRONG[j]) STRONG[j] = root.r;
      for(const k of down[j]) st.push(k); } }
})();

const c=document.getElementById('c'), g=c.getContext('2d');
let view={x:20,y:20,s:0.55}, drag=null, sel=null, filt=null;
const css = v => getComputedStyle(document.documentElement)
  .getPropertyValue(v).trim();
let focus = new Set();
// A selected principle under the landmarks view: which landmarks rest on it,
// and which of those name it directly.
let PSEL = null;
const INTRO = document.getElementById('side').innerHTML;
function esc(s){ return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;')
  .replace(/>/g,'&gt;').replace(/"/g,'&quot;'); }
function link(t,u){ return u ? '<a href="'+u+'" target=_blank rel=noopener>'+t+'</a>' : t; }
function tagHtml(t,col){ return '<span class=tag style="background:'+col+'">'+t+'</span>'; }
function shortName(f){ return f.split('.').pop(); }
function bracketHtml(b){
  const rev = b.rev.length
    ? b.rev.map(r => link(tagHtml(esc(r.p), css('--amber')), r.pu) + ' by '
        + link('<code>'+esc(shortName(r.by))+'</code>', r.bu)).join(' ')
    : '<span class=p>no reversal published</span>';
  const used = b.used === null ? '<span class=p>no proof published</span>'
    : b.used.length
    ? b.used.map(r => link(tagHtml(esc(r.p), css('--amber')), r.pu)).join(' ')
    : '<span class=p>none</span>';
  return '<div class=sec>Bracket</div>'
    + '<div class=row>Needed, by reversal: ' + rev + '</div>'
    + '<div class=row>Used by the proof'
    + (b.via ? ' ' + link('<code>'+esc(shortName(b.via))+'</code>', b.vu) : '')
    + ': ' + used + '</div>';
}
function pairHtml(p){
  const ml = p.ml
    ? 'Matches ' + link('<code>'+esc(p.ml)+'</code>', p.mlu)
      + ' <span class=p>(' + p.src + ')</span>'
    : 'Discharged from Lean core; no library declaration to match';
  return '<div class=sec>Comparator</div><div class=row>' + ml + '</div>'
    + '<div class=row>' + link('the pair', p.dir) + ' &middot; '
    + link('its formalization.yaml entry', p.yaml) + '</div>';
}
let DOWN = null;
function landmarksOn(n){
  if(!DOWN){ DOWN = N.map(()=>[]);
    for(const m of N) for(const u of m.up) DOWN[u].push(m.id); }
  const seen = new Set(), st = [n.id];
  while(st.length){ const i = st.pop();
    for(const j of DOWN[i]) if(!seen.has(j)){ seen.add(j); st.push(j); } }
  const direct = new Set(n.dn.filter(j => N[j].lm));
  // A LANDMARK THAT IS A STATEMENT sits upstream of its own proof: the proof
  // mentions the statement, not the other way round. So `ExactIVT01` has no
  // path from the principles its proof takes, and is found through the
  // bracket instead, where the proof names them itself.
  for(const m of N){
    if(m.lm && m.br && m.br.via && m.br.via !== m.f && m.br.used
       && m.br.used.some(u => u.p === n.n)){ seen.add(m.id); direct.add(m.id); } }
  const lms = [...seen].map(i => N[i]).filter(m => m.lm);
  lms.sort((a,b) => a.lm.localeCompare(b.lm));
  return {lms: lms, direct: direct};
}
function principlePane(n, s){
  const got = landmarksOn(n), lms = got.lms;
  s.innerHTML = '<h3>'+link(esc(n.n), n.u)+'</h3><div class=p>'+esc(n.f)
    + ' &middot; principle</div>'
    + '<p><b>'+lms.length+'</b> landmark'+(lms.length===1 ? ' rests' : 's rest')
    + ' on it'+(lms.length ? ':' : '.')+'</p>'
    + (lms.length ? '<ul class=lms>' + lms.map(m => '<li><a href="#" data-id="'
        + m.id + '">' + esc(m.lm) + '</a>'
        + (got.direct.has(m.id) ? '' : ' <span class=p>(through others)</span>')
        + '</li>').join('') + '</ul>' : '');
  s.querySelectorAll('a[data-id]').forEach(a => a.addEventListener('click', e => {
    e.preventDefault(); pick(N[+a.dataset.id]); }));
}
let keepEdge = new Set();
let sideHead = [];
let coneCut = 0;
function inFocus(n){ return focus.has(n); }
function visible(n){
  if(n.k==='axiom' || n.k==='principle') return true;
  // A selected node's neighbourhood shows THROUGH the landmarks-only filter.
  // Otherwise clicking a landmark hides exactly the dependencies the click was
  // asking about, since almost nothing a landmark rests on is itself a
  // landmark.
  if(inFocus(n)) return true;
  if(document.getElementById('onlylm').checked && !n.lm) return false;
  // A LANDMARK IS NEVER A LEMMA. `sq_two_irrational` is a leaf -- nothing in
  // the library rests on it, which is what a headline result usually looks
  // like -- so the lemma filter hid the oldest theorem in the tree while the
  // landmarks toggle counted it. The graph said `only landmarks (7)` and drew
  // six, and its era axis began at 1874.
  if(n.lm) return true;
  if(document.getElementById('onlyax').checked && !n.i.length) return false;
  if(!document.getElementById('lemmas').checked && n.leaf) return false;
  if(filt && !n.f.toLowerCase().includes(filt)) return false;
  return true;
}
let DPR = 1;
function resize(){
  DPR = Math.max(1, window.devicePixelRatio || 1);
  c.width = Math.round(innerWidth * DPR);
  c.height = Math.round((innerHeight - 41) * DPR);
  c.style.width = innerWidth + 'px';
  c.style.height = (innerHeight - 41) + 'px';
  c.style.marginTop = '41px';
  draw(); }
const LABELS = [];
function X(n){ return n.px!==undefined ? n.px : n.x; }
function Y(n){ return n.py!==undefined ? n.py : n.y; }
function draw(){
  // The rail is PINNED TO THE VIEWPORT, not placed in the graph. In world
  // space it sat at x=40 and any layout reaching left of that -- a cone's
  // ancestor columns, the earliest landmarks -- drew its labels straight
  // through the boxes. Recomputing its world position from a fixed screen
  // position each frame keeps it on the left edge at every zoom, and because
  // it goes through the same px/py override as everything else, its edges and
  // hit-testing need no special case.
  RAIL.forEach((n,i)=>{
    n.px = (14 - view.x)/view.s;
    n.py = (70 + i*24 - view.y)/view.s; });
  const line=css('--line'), red=css('--red'), blue=css('--blue'),
        amber=css('--amber'), ink=css('--ink');
  g.setTransform(1,0,0,1,0,0); g.clearRect(0,0,c.width,c.height);
  g.setTransform(view.s*DPR,0,0,view.s*DPR,view.x*DPR,view.y*DPR);
  LABELS.length = 0;
  const hi = document.getElementById('classical').checked;
  const all = document.getElementById('alledges').checked;
  // 75217 strokes is a wash, not a drawing. By default only the edges that
  // carry the picture's claim are drawn -- each axiom to what introduces it
  // -- and the rest are opt-in.
  if(all){ g.lineWidth = 0.4/view.s; g.globalAlpha=0.35;
    // Coloured by the strongest assumption reaching the EDGE'S TARGET, so a
    // region's price is legible without clicking into it. A single grey pass
    // drew 83k strokes that said only "there are dependencies".
    for(const [a,b] of E){ const A=N[a], B=N[b];
      if(!visible(A)||!visible(B)) continue;
      g.strokeStyle = STRONG[a] >= 0 ? 'hsl('+railHue(STRONG[a])+' 62%% 45%%)'
                                     : line;
      g.beginPath(); g.moveTo(X(A),Y(A)); g.lineTo(X(B),Y(B)); g.stroke(); }
    g.globalAlpha=1; }
  else { g.lineWidth = 0.5/view.s;
    // Axioms AND principles, always. A principle's edges used to appear only
    // while its consumer was selected, so the standing question -- what rests
    // on LPO, on MP, on a locator -- was invisible until you already knew where
    // to click. Faint when nothing is selected, solid when the edge touches the
    // selection, so the always-on layer never competes with the answer.
    for(const [a,b] of E){ const A=N[a], B=N[b];
      if((A.k!=='axiom' && A.k!=='principle') || !visible(B)) continue;
      const hot = !PSEL && sel && (B===sel || A===sel);
      g.globalAlpha = hot ? 0.95 : (A.k==='principle' ? 0.22 : 0.5);
      g.lineWidth = (hot ? 1.1 : A.k==='principle' ? 0.4 : 0.5)/view.s;
      g.strokeStyle = railCol(A);
      g.beginPath(); g.moveTo(X(A),Y(A)); g.lineTo(X(B),Y(B)); g.stroke(); }
    // WHAT EACH LANDMARK RESTS ON, drawn directly. An axiom's own consumers
    // are the declarations that introduce it, and those are almost never
    // landmarks -- so under `only landmarks` every rail edge was filtered out
    // and the view showed a row of results resting on nothing. The dependency
    // is transitive and the edge says so.
    if(document.getElementById('onlylm').checked){
      for(const n of N){
        if(!n.lm || !visible(n)) continue;
        for(const ax of n.a){
          const A = N.find(m => m.n === ax);
          if(!A) continue;
          const hot = sel && (n===sel);
          g.globalAlpha = hot ? 0.9 : 0.3;
          g.lineWidth = (hot ? 1.1 : 0.5)/view.s;
          g.strokeStyle = railCol(A);
          g.beginPath(); g.moveTo(X(A),Y(A)); g.lineTo(X(n),Y(n)); g.stroke(); } } }
    g.globalAlpha=1; }
  // A SELECTED PRINCIPLE draws to the landmarks resting on it: solid where the
  // landmark names the principle itself, dashed where it rests on it through
  // other declarations. Nothing that is not a landmark is lit.
  if(PSEL){
    g.strokeStyle = railCol(sel); g.globalAlpha = 0.9; g.lineWidth = 1.2/view.s;
    for(const id of PSEL.all){ const m = N[id];
      if(!visible(m)) continue;
      g.setLineDash(PSEL.direct.has(id) ? [] : [5/view.s, 4/view.s]);
      g.beginPath(); g.moveTo(X(sel),Y(sel)); g.lineTo(X(m),Y(m)); g.stroke(); }
    g.setLineDash([]); g.globalAlpha = 1; }
  if(sel && !PSEL){ g.lineWidth=1.0/view.s; g.globalAlpha=0.85;
    // Every edge INSIDE the cone, not just the selected node's own -- and each
    // in the colour of the strongest assumption reaching its target, so the
    // cone shows where its price enters rather than only its shape.
    for(const [a,b] of E){ const A=N[a], B=N[b];
      if(!inFocus(A) || !inFocus(B)) continue;
      if(keepEdge.size && !keepEdge.has(a + ':' + b)) continue;
      // Coloured by what the SOURCE carries, not by what the target inherits.
      // Target-colouring gave one node's out-edges a dozen different colours,
      // which reads as the source EMITTING them -- the picture said every
      // strength originated at `Divides`. What flows along an edge is the
      // source's cost.
      g.strokeStyle = STRONG[a] >= 0 ? 'hsl('+railHue(STRONG[a])+' 62%% 45%%)'
                                     : line;
      g.beginPath(); g.moveTo(X(A),Y(A)); g.lineTo(X(B),Y(B)); g.stroke(); }
    g.globalAlpha=1; }
  for(const n of N){ if(!visible(n)) continue;
    if(n.k==='axiom' || n.k==='principle'){
      const isAx = n.k==='axiom';
      g.fillStyle = railCol(n);
      // The box is measured from its text, not fixed at 92. `CountableBoolChoice`
      // and `CountableNatChoice` overflowed a fixed box and were painted as
      // `untableBoolChoic` -- a label clipped to something that reads as a
      // different name is worse than no label, and worst on the principles,
      // whose whole point is which one is being spent.
      // Screen-sized, because the rail is screen-placed: a box in world units
      // grows and shrinks with the zoom while its slot does not.
      const fu = 10/view.s;
      g.font='600 '+fu+'px ui-sans-serif, system-ui';
      const bw = g.measureText(n.n).width + 12/view.s, bh = 18/view.s;
      g.fillRect(X(n), Y(n)-bh/2, bw, bh);
      g.fillStyle='#fff';
      g.textAlign='left'; g.fillText(n.n, X(n)+6/view.s, Y(n)+3.4/view.s);
      LABELS.push({n:n, x0:X(n), y0:Y(n)-bh/2, x1:X(n)+bw, y1:Y(n)+bh/2});
      g.textAlign='left';
      continue; }
    const cl = n.a.indexOf('Classical.choice') >= 0;
    g.fillStyle = (hi&&cl) ? red
                : n.i.length ? amber
                : 'hsl(' + HUE[n.m] + ' 55%% 52%%)';
    const lm = !!n.lm;
    const r = (n===sel?4.5:lm?3.4:n.i.length?2.4:1.5)
              /Math.max(0.6,Math.sqrt(view.s));
    g.beginPath(); g.arc(X(n),Y(n),r,0,6.283); g.fill();
    if(lm){ g.strokeStyle=ink; g.lineWidth=1.1/view.s; g.stroke(); } }
  // Landmark names, drawn last so nothing covers them, and only when the
  // view is close enough for them not to collide into a smear.
  // Labels whenever there are FEW ENOUGH to read, not only when zoomed in.
  // The old gate was `view.s > 0.9`, so the landmarks view -- the one a reader
  // opens to see named results -- showed sixty unlabelled dots until they
  // discovered they could zoom. A count is the right condition: what makes
  // labels illegible is collision, and collision is about how many are on
  // screen rather than how far in the view is.
  // The timeline's own axis note. Ticks were considered and rejected: x is
  // RANK, so a tick labelled 1600 would sit at 8%% across while a reader
  // reading distance as elapsed time expects 85%% -- the ticks would be labels
  // on positions rather than a scale, and misleading precisely because they
  // look like one. The ends are honest, and the note says
  // what the spacing means.
  if(!sel && document.getElementById('onlylm').checked){
    const lms = N.filter(n=>n.lm && n.yr!==null && n.yr!==undefined && visible(n));
    if(lms.length > 1){
      lms.sort((a,b)=>X(a)-X(b));
      const a=lms[0], z=lms[lms.length-1];
      g.fillStyle=css('--dim')||'#888';
      g.font='600 '+(15/view.s)+'px ui-sans-serif, system-ui';
      const yTop = Math.min(...lms.map(n=>Y(n))) - 46;
      g.fillText('earliest -- '+a.yr, X(a), yTop);
      g.fillText(z.yr+' -- latest', X(z)-90, yTop);
      g.font=(12/view.s)+'px ui-sans-serif, system-ui';
      g.fillText('left to right is chronological order; spacing is rank, not '
        +'elapsed time', X(a), yTop-22/view.s);
      g.strokeStyle=css('--line'); g.lineWidth=1/view.s;
      g.beginPath(); g.moveTo(X(a), yTop+10/view.s);
      g.lineTo(X(z), yTop+10/view.s); g.stroke();
    }
  }

  // With a selection, the labels to draw are the ANSWER -- the node, what it
  // rests on, and what rests on it -- and every other name is context. Drawn
  // faint rather than dropped, so the reader keeps the shape of the graph
  // around the thing they asked about.
  const shownLm = sel
    ? N.filter(n => visible(n) && (inFocus(n) || n.lm))
    : N.filter(n => n.lm && visible(n));
  if(sel || view.s > 0.9 || shownLm.length <= 140){ g.fillStyle=ink;
    // In timeline mode the font is fixed in WORLD units, so the lane packing
    // computed at layout time and the text measured at draw time agree. Sizing
    // it in screen units made a 15px label 60 world units wide at s=0.25, four
    // times what the packing reserved, and every label after the third
    // collided away.
    const tl = document.getElementById('onlylm').checked;
    const fs = tl ? 22*view.s
             : Math.max(9, Math.min(15, 13/Math.sqrt(Math.max(0.35,view.s))));
    g.font='600 '+(fs/view.s)+'px ui-sans-serif, system-ui';
    const done=new Set(), placed=[];
    // Collision avoidance, greedy by importance. Sixty labels in one band
    // overlapped into an unreadable smear; a label that cannot be placed
    // clear of an earlier one is SKIPPED rather than drawn over it, and
    // zooming in frees space so the skipped ones appear. Most-depended-upon
    // first, so what survives a crowded view is what the library leans on.
    // Focus first, so a crowded view spends its space on the answer before it
    // spends it on context -- the greedy placement below SKIPS what collides,
    // and without this the most-depended-upon landmarks would take the room and
    // the selected node's own dependencies would be the ones dropped.
    const ordered = shownLm.slice().sort((a,b)=>
      (inFocus(b)-inFocus(a)) || (b.d-a.d));
    for(const n of ordered){
      // The rail draws its own name inside its box; the label pass would print
      // it a second time, offset, once a cone put the rail in focus.
      if(n.k==='axiom' || n.k==='principle') continue;
      const foc = inFocus(n);
      // A dependency that is not a landmark has no `lm` name, so it is labelled
      // by its declaration -- which is what the reader clicked to find out.
      const s = (n.lm || n.n || '').slice(0,44);
      if(!s) continue;
      if(n.lm){ if(done.has(n.lm)) continue; }
      // A landmark is a named result; a helper is a step. Drawing both at one
      // size made a cone of 460 lemma names shout as loudly as the theorem
      // they build, and the reader had no way to tell which line was the
      // answer.
      const lf = n.lm ? fs : fs*0.52;
      g.font='600 '+(lf/view.s)+'px ui-sans-serif, system-ui';
      const w = g.measureText(s).width, h = lf/view.s;
      const x = X(n)+7/view.s, y = Y(n)-6/view.s;
      let clash=false;
      for(const r of placed){
        if(x < r.x+r.w && x+w > r.x && y-h < r.y && y > r.y-r.h){
          clash=true; break; } }
      // Focus labels skip on collision like any other. Exempting them meant
      // 480 cone names drew on top of each other into a white smear -- worse
      // than the unlabelled dots they replaced. They are SORTED first instead,
      // so they win the space they can use, and zooming frees the rest.
      if(clash) continue;
      placed.push({x:x,y:y,w:w,h:h}); if(n.lm) done.add(n.lm);
      LABELS.push({n:n, x0:x, y0:y-h, x1:x+w, y1:y+h*0.35});
      g.globalAlpha = (sel && !foc) ? 0.28 : 1;
      // A PLATE, not a halo. The label was legible over the edges because it
      // was stroked in white underneath at 3.5px and then filled -- which at
      // the landmark zoom is a fat soft outline around every glyph, and reads
      // as blur. The axiom tags were always crisp because they sit on a solid
      // rectangle and are only filled; landmarks now do the same.
      const pad = 3/view.s;
      g.fillStyle = css('--bg') || '#fff';
      g.globalAlpha *= 0.82;
      g.fillRect(x - pad, y - h + pad*0.5, w + pad*2, h + pad);
      g.globalAlpha = (sel && !foc) ? 0.28 : 1;
      g.fillStyle=ink; g.fillText(s, x, y); }
    g.globalAlpha=1; }
  for(const h of sideHead){
    g.font='700 '+(26/view.s)+'px ui-sans-serif, system-ui';
    g.fillStyle=css('--dim')||'#888'; g.textAlign='center';
    g.fillText(h.s, h.x, h.y); g.textAlign='left'; }
  document.getElementById('status').textContent =
    N.filter(visible).length + ' shown'
    + (coneCut ? ' \u00b7 cone of ' + coneCut + ' -- framed on the '
                 + 'neighbourhood, zoom out for the rest' : '');
}
function at(px,py){ const x=(px-view.x)/view.s, y=(py-view.y)/view.s;
  let best=null, bd=1e9;
  for(const n of N){ if(!visible(n)) continue;
    const d=(X(n)-x)*(X(n)-x)+(Y(n)-y)*(Y(n)-y); if(d<bd){ bd=d; best=n; } }
  if(bd < 64) return best;
  // Then the labels, in world coordinates, most recently drawn first so the
  // one on top of a stack wins.
  for(let i=LABELS.length-1; i>=0; i--){ const L=LABELS[i];
    if(x>=L.x0 && x<=L.x1 && y>=L.y0 && y<=L.y1) return L.n; }
  return null; }
c.addEventListener('mousedown', e=>{ drag={x:e.clientX-view.x,
  y:e.clientY-view.y, moved:false}; c.classList.add('drag'); });
addEventListener('mouseup', e=>{ if(drag && !drag.moved)
    pick(at(e.clientX, e.clientY-41));
  drag=null; c.classList.remove('drag'); });
addEventListener('mousemove', e=>{ if(!drag) return; drag.moved=true;
  view.x=e.clientX-drag.x; view.y=e.clientY-drag.y; draw(); });
c.addEventListener('wheel', e=>{ e.preventDefault();
  const k=Math.exp(-e.deltaY*0.001), mx=e.clientX, my=e.clientY-41;
  view.x=mx-(mx-view.x)*k; view.y=my-(my-view.y)*k; view.s*=k; draw(); },
  {passive:false});
// The view a selection returns to: the opening frame, or the frame the last
// change of mode chose.
let HOME = null;
function clearSel(){
  sel=null; PSEL=null; focus=new Set(); keepEdge=new Set(); sideHead=[]; coneCut=0;
  for(const m of N){ m.px=undefined; m.py=undefined; }
  document.getElementById('side').innerHTML=INTRO; }
function pick(n){ sel=n; const s=document.getElementById('side');
  // DESELECTING RETURNS TO THE OPENING VIEW, restored exactly rather than
  // refitted: the rail is pinned to the screen, so a refit depends on wherever
  // the view last was.
  if(!n){ clearSel(); if(HOME) view={...HOME}; draw(); return; }
  PSEL = null;
  if(n.k==='principle' && document.getElementById('onlylm').checked){
    const got = landmarksOn(n);
    PSEL = {all: got.lms.map(m => m.id), direct: got.direct};
    for(const m of N){ m.px=undefined; m.py=undefined; }
    focus = new Set([n, ...got.lms]); keepEdge = new Set(); sideHead = []; coneCut = 0;
    fitTo(N.filter(visible)); principlePane(n, s); draw(); return; }
  const seen=new Set(), stack=n.up.slice(), first={};
  while(stack.length){ const i=stack.pop(); if(seen.has(i)) continue;
    seen.add(i); for(const a of N[i].i){ (first[a]=first[a]||[]).push(N[i].f); }
    for(const u of N[i].up) stack.push(u); }
  // Frame the NEIGHBOURHOOD: the node, what it rests on, and every landmark
  // that rests on it -- the two questions a reader has on clicking. Fitting to
  // the whole graph left the answer scattered across a viewport scaled for six
  // thousand nodes.
  const idx = N.indexOf(n);
  // The WHOLE cone, both ways -- everything the node rests on transitively and
  // everything transitively resting on it. Direct neighbours alone answered
  // "what did this use" and left "what does it ultimately cost" to the panel's
  // numbers, which is the question the picture exists to answer.
  const upAll = new Set(), dnAll = new Set();
  (function(){
    const st = n.up.slice();
    while(st.length){ const i = st.pop();
      if(upAll.has(i)) continue; upAll.add(i);
      for(const u of N[i].up) st.push(u); }
    const down = N.map(()=>[]);
    for(const m of N) for(const u of m.up) down[u].push(N.indexOf(m));
    const st2 = [idx];
    while(st2.length){ const i = st2.pop();
      for(const j of down[i]){ if(dnAll.has(j)) continue;
        dnAll.add(j); st2.push(j); } }
  })();
  const keep = new Set([n]);
  for(const i of upAll) keep.add(N[i]);
  for(const j of dnAll) keep.add(N[j]);
  focus = keep;
  // Laid out by DEPTH from the selection: ancestors to the left one column per
  // step, descendants to the right, stacked within a column. A single column
  // per side worked for 44 direct dependencies and cannot hold 461 -- and a
  // cone drawn by depth is the shape the reader is asking about anyway.
  for(const m of N){ m.px = undefined; m.py = undefined; }
  if(document.getElementById('onlylm').checked){
    const depth = new Map([[idx, 0]]);
    (function(){
      let front = [idx], d = 0;
      while(front.length && d < 40){ d++; const next = [];
        for(const i of front) for(const u of N[i].up)
          if(!depth.has(u)){ depth.set(u, -d); next.push(u); }
        front = next; }
      const down = N.map(()=>[]);
      for(const m of N) for(const u of m.up) down[u].push(N.indexOf(m));
      front = [idx]; d = 0;
      while(front.length && d < 40){ d++; const next = [];
        for(const i of front) for(const j of down[i])
          if(!depth.has(j)){ depth.set(j, d); next.push(j); }
        front = next; }
    })();
    // TRANSITIVE REDUCTION over the cone. Every edge here is a genuine direct
  // reference -- a Lean proof term mentions every constant it uses, so a
  // theorem three steps above `IsPrime` still names it -- but 40 of IsPrime's
  // 52 out-edges are ALSO reachable by a longer path, and drawing them makes a
  // fan that says only "many things use this". Keeping just the edges no
  // longer path implies leaves the shape: a to b and b to d, not a to d.
  keepEdge = new Set();
  (function(){
    const inF = new Set(); for(const m of keep) inF.add(N.indexOf(m));
    const succ = new Map();
    for(const [a,b] of E){ if(!inF.has(a) || !inF.has(b)) continue;
      if(!succ.has(a)) succ.set(a, []); succ.get(a).push(b); }
    for(const [a, outs] of succ){
      const os = new Set(outs);
      // What a reaches in TWO OR MORE steps. Any direct successor also in
      // that set is implied by a longer path and is dropped.
      const seen = new Set(), st = [];
      for(const b of outs) for(const c of (succ.get(b) || [])) st.push(c);
      while(st.length){ const j = st.pop();
        if(seen.has(j)) continue; seen.add(j);
        for(const c of (succ.get(j) || [])) st.push(c); }
      for(const b of outs) if(!seen.has(b)) keepEdge.add(a + ':' + b);
    }
  })();
  const cols = new Map();
    for(const [i, d] of depth){ if(d === 0) continue;
      if(!cols.has(d)) cols.set(d, []); cols.get(d).push(i); }
    // Wrapped: a depth with 200 members is a 5,000-unit column, and fitting it
    // zooms to where no name can be read. Sub-columns keep the cone roughly as
    // wide as it is tall, which is the shape a screen can hold.
    // Column offsets ACCUMULATE outward. Computing each depth's x from its
    // own sub-column count made them non-monotonic: depth 1 had 52 members and
    // wrapped to two sub-columns ending at 720, while depth 2 had two members
    // and sat at 600 -- so the deeper nodes were drawn LEFT of the shallower
    // ones and the far end of the cone landed off-screen behind the panel.
    // Reading the cone outward requires x to increase with depth, always.
    const PER = 26, SUB = 230;
    for(const side of [-1, 1]){
      const ds = [...cols.keys()].filter(d => Math.sign(d) === side)
                                 .sort((a,b) => Math.abs(a) - Math.abs(b));
      let off = 120;
      for(const d of ds){
        const list = cols.get(d), subs = Math.ceil(list.length/PER);
        off += SUB;
        list.forEach((i, k) => { const m = N[i];
          const c = Math.floor(k/PER), r = k%%PER;
          m.px = n.x + side*(off + c*SUB);
          m.py = n.y + (r - Math.min(list.length, PER)/2)*26; });
        off += (subs - 1)*SUB;
      }
    }
  }
  // Frame what can be READ, not everything that is drawn. The whole cone is
  // on screen and coloured -- 461 nodes for the fundamental theorem -- but a
  // viewport scaled to hold it puts every name below a pixel tall, which is
  // the smear this replaced. The camera goes to the selected node and its
  // direct neighbours; the rest of the cone extends past the edges and comes
  // into view, with its labels, as the reader zooms out and in.
  // Headings over the two sides. "Which of these does it rest on and which
  // rest on it" was not answerable from the picture: both sides were columns
  // of small names in the same colour, and the only cue was which side of the
  // node they sat on -- which is a convention the reader has to be told.
  sideHead = [];
  if(document.getElementById('onlylm').checked){
    const anyL = [...keep].some(m => m.px !== undefined && m.px < n.x);
    const anyR = [...keep].some(m => m.px !== undefined && m.px > n.x);
    const top = Math.min(...[...keep].filter(m=>m.px!==undefined)
                                     .map(m=>m.py)) - 46;
    if(anyL) sideHead.push({x: n.x - 250, y: top, s: 'rests on \u2192'});
    if(anyR) sideHead.push({x: n.x + 250, y: top, s: '\u2192 rests on it'});
  }
  // Frame the WHOLE cone when it can be read. 69 nodes for the infinitude of
  // primes fits legibly; 480 for the fundamental theorem does not, and a
  // viewport scaled to hold those puts every name under a pixel. The cutoff is
  // the only honest knob here, and the status line says which view you got so
  // a truncated frame is never silent.
  const whole = [...keep].filter(visible);
  const readable = [n];
  for(const u of n.up) readable.push(N[u]);
  for(const m of N) if(m.up.indexOf(idx) >= 0) readable.push(m);
  const near = whole.length <= 160 ? whole : readable.filter(visible);
  coneCut = whole.length > 160 ? whole.length : 0;
  if(near.length > 1) fitTo(near, 110);

  const tag=(t,col)=>'<span class=tag style="background:'+col+'">'+t+'</span>';
  if(n.k==='principle'){ principlePane(n, s); draw(); return; }
  s.innerHTML = '<h3>'+link(esc(n.n), n.u)+'</h3>'
    + '<div class=p>'+n.f+'<br>'+n.m+' &middot; '+n.k+' &middot; layer '+n.l+'</div>'
    + (n.lm ? '<p><b>Landmark:</b> '+esc(n.lm)+'</p>' : '')
    + (n.br ? bracketHtml(n.br) : '')
    + (n.pr ? pairHtml(n.pr) : '')
    + '<p>'+(n.a.length ? n.a.map(a=>tag(a, a==='Classical.choice'
        ? css('--red') : css('--blue'))).join('') : '<b>no axioms</b>')+'</p>'
    // Principles are a SEPARATE line and separately labelled, because they are
    // a different kind of cost: an axiom is what the kernel assumed under the
    // proof, a principle is what the STATEMENT takes as a hypothesis. Merging
    // them into one row of tags would say a theorem "depends on LLPO" in the
    // same voice as "depends on propext", and the whole point of this
    // development is that those are not the same claim.
    + (n.p && n.p.length
        ? '<p><b>Takes as hypotheses:</b> '
          + n.p.map(x=>tag(x, css('--amber'))).join('')
          + '</p><div class=p>Named in its statement, so this is what the '
          + 'THEOREM costs. The axioms above are what its proof used.</div>'
        : '<div class=p><b>No principle in its statement.</b> A hypothesis '
          + 'can supply the same strength as data -- a selector, a readout, a '
          + 'structure carrying a decision -- so this is a lower bound on '
          + 'what the theorem assumes, not a proof that it assumes '
          + 'nothing.</div>')
    + '<p><b>'+n.up.length+'</b> direct dependencies, <b>'+seen.size
    + '</b> in its whole cone; <b>'+n.dn.length+'</b> depend on it.</p>'
    + (n.i.length ? '<p>Introduces '+n.i.join(', ')
        + ' -- no dependency of this uses it.</p>' : '')
    + '<p class=p>Where each axiom first entered beneath it:</p><ul>'
    + (Object.keys(first).map(a=>'<li><b>'+a+'</b> -- '+first[a].length
        + ' entry point' + (first[a].length>1?'s':'') + ', e.g. <code>'
        + first[a].slice(0,3).join('</code>, <code>')+'</code></li>').join('')
       || '<li class=p>nothing -- this rests on no axiom</li>')
    + '</ul>';
  draw(); }
// THE LANDMARK TIMELINE. In landmarks-only mode the graph layout is the wrong
// one: it places six thousand declarations by dependency depth, and the sixty
// dated results end up in a narrow band with most of the canvas empty. Here
// the x axis is the DATE the idea was fixed and each landmark takes a lane
// wide enough for its own label, so nothing collides and every name is
// readable at the default zoom. Dependency edges still draw, so a reader sees
// what rests on what ACROSS the centuries rather than within a layer.
let lmLaid = false;
function layoutLandmarks(){
  if(lmLaid) return; lmLaid = true;
  const lm = N.filter(n=>n.lm && n.yr!==null && n.yr!==undefined);
  if(!lm.length) return;
  lm.sort((a,b)=>a.yr-b.yr);
  // x by RANK, not by year. A linear axis piles twenty modern results on top
  // of each other; a square-root axis spreads the sparse ancient end and
  // crushes the dense modern one, which is the same mistake mirrored. Rank
  // keeps the thing that carries the meaning -- the ORDER in which the ideas
  // were fixed -- and spends the axis evenly, and the year is in every label
  // so nothing is lost by not spacing to scale.
  const W = 1000;
  lm.forEach((n,i) => { n.x = (i/Math.max(1,lm.length-1))*W; });
  // Lanes: walk left to right, put each landmark in the lowest lane whose
  // last occupant ended before this one starts.
  const ends = [];
  for(const n of lm){
    const need = n.lm.length*12 + 40;
    let k = ends.findIndex(e => e <= n.x);
    if(k < 0){ k = ends.length; ends.push(0); }
    ends[k] = n.x + need;
    n.y = k*36;
  }
  // Axioms and principles keep their own column, to the left of the era.
  N.filter(n=>n.l<0).forEach((n,i)=>{ n.x = -200; n.y = i*24; });
}

// Fit the view to a set of nodes, with room for their labels.
function fitTo(ns, pad){
  if(!ns.length) return;
  let x0=1e9,y0=1e9,x1=-1e9,y1=-1e9;
  for(const n of ns){ x0=Math.min(x0,X(n)); y0=Math.min(y0,Y(n));
                      y1=Math.max(y1,Y(n));
                      // A label extends to the RIGHT of its node, so fitting
                      // to node positions alone clipped every name in the last
                      // column against the detail panel.
                      x1=Math.max(x1, X(n) + ((n.lm||n.n||'').length*12+30)); }
  const m = pad===undefined ? 90 : pad;
  // The canvas is full-window and the detail panel OVERLAYS its right 330px,
  // so fitting to `c.width` pushed the last column of labels underneath it.
  // CSS PIXELS, not the backing store. `c.width` counts device pixels since
  // the canvas was made HiDPI, so this fitted the layout to a viewport twice
  // the real width: every label came out at double size and the last two
  // landmarks fell off the right edge.
  const w = c.width/DPR - 330, h = c.height/DPR;
  const s = Math.min((w-2*m)/Math.max(1,x1-x0), (h-2*m)/Math.max(1,y1-y0));
  view.s = Math.max(0.05, Math.min(6, s));
  view.x = w/2 - (x0+x1)/2*view.s;
  view.y = h/2 - (y0+y1)/2*view.s;
}
// Changing a mode re-fits: the landmarks view used to leave the camera where
// the full graph had put it, so sixty nodes sat scattered across a viewport
// scaled for six thousand.
['lemmas','onlyax','classical','alledges','onlylm'].forEach(id =>
  document.getElementById(id).addEventListener('change', () => {
    if(document.getElementById('onlylm').checked) layoutLandmarks();
    if(sel) clearSel();
    fitTo(N.filter(visible)); HOME={...view}; draw(); }));
document.getElementById('q').addEventListener('input', e=>{
  filt = e.target.value.trim().toLowerCase() || null; draw(); });
addEventListener('resize', resize);
// The landmarks view is the DEFAULT now, and a checkbox that starts checked
// never fires `change` -- so the timeline layout ran only if you toggled it
// off and on again. The page opened with landmark labels over a
// force-directed scatter, under an axis note promising chronological order:
// the caption was true of a layout that had not been applied.
if(document.getElementById('onlylm').checked) layoutLandmarks();
resize();
fitTo(N.filter(visible));
HOME={...view};
draw();
</script>
"""


def caption_counts(d):
    """The two numbers the page's caption states: declarations, dependencies.

    **One rule, one place.** `figclaims.py` recomputes these to check the
    drawing, and for a while it recomputed them DIFFERENTLY -- `len(rows)` over
    the whole export against this function's root-excluding count, a gap of
    exactly the 13 axiom and principle nodes. Both were internally honest and
    the figure was reported WRONG while rendering the number it meant. That is
    the ledger-parser defect in a new place: one set computed twice, disagreeing
    on the cases nobody looked at.

    The roots are DRAWN; they are not DECLARATIONS, and the caption says
    declarations. Edges out of a root are the picture's frame -- an axiom
    entering the library -- rather than one declaration depending on another.
    """
    roots = {"axiom", "principle"}
    decls = [n for n in d["nodes"] if n["k"] not in roots]
    ax = {i for i, n in enumerate(d["nodes"]) if n["k"] in roots}
    dep_edges = [e for e in d["edges"] if e[0] not in ax]
    return len(decls), len(dep_edges)


def page():
    d = graph()
    if d is None:
        return None
    down = set(a for a, _ in d["edges"])
    lemmas = sum(1 for i, n in enumerate(d["nodes"])
                 if n["k"] == "theorem" and i not in down)
    # Selection, not a drop -- see `caption_counts`, which both this and
    # `figclaims.py` now read the rule from. This reasoning lived in
    # `dropped-allow.txt` until a refactor made that entry stale; it belongs
    # beside the code it explains rather than in a registry row.
    roots = {"axiom", "principle"}
    decls = [n for n in d["nodes"] if n["k"] not in roots]
    ax = {i for i, n in enumerate(d["nodes"]) if n["k"] in roots}
    dep_edges = [e for e in d["edges"] if e[0] not in ax]
    # The interpreter DETECTS a stray `%` in the template and does not LOCATE
    # it: the traceback points at this line, not at the offending character,
    # and finding it means grepping a 300-line template. That happened today
    # over a `%` in a comment about a percentage. So catch and say where
    #. Detection was never the gap.
    try:
        return _render(PAGE, decls, dep_edges, lemmas, d)
    except (TypeError, ValueError) as e:
        import re as _re
        # Consume `%%` pairs FIRST, then look for a survivor. Scanning for
        # `%` not followed by `%` reports the second half of every correctly
        # escaped pair -- `55%% 52%%` came back as two violations, so the
        # diagnostic accused the lines that were already right.
        bad = []
        for i, ln in enumerate(PAGE.splitlines(), 1):
            rest = _re.sub(r"%%", "", ln)
            rest = _re.sub(r"%\([a-z]+\)[sd]", "", rest)
            if "%" in rest:
                bad.append((i, ln))
        if bad:
            where = "\n".join(f"      template line {i}: {ln.strip()[:70]}"
                               for i, ln in bad[:5])
            raise SystemExit(
                f"  dag.py: the page template has {len(bad)} unescaped `%`.\n"
                f"  The whole page is one Python format string, so a literal\n"
                f"  percent must be written `%%` -- in CSS, in JS, and in\n"
                f"  comments alike:\n{where}") from e
        raise


def _render(PAGE, decls, dep_edges, lemmas, d):
    return PAGE % {
        "marker": MARKER,
        "count": len(decls),
        "edges": len(dep_edges),
        "lemmas": lemmas,
        "intro": sum(1 for n in d["nodes"] if n["i"]),
        "land": sum(1 for n in d["nodes"] if n.get("lm")),
        "data": json.dumps(d, separators=(",", ":")),
    }


def main():
    ap = argparse.ArgumentParser(description="The dependency DAG, as a page.")
    ap.add_argument("--record", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    fresh = page()
    if fresh is None:
        target = ROOT / "figures" / "dag.html"
        # SKIPPING THE FRESHNESS QUESTION IS FINE; SKIPPING VALIDITY IS NOT,
        # and an ABSENT file is the case where the note asserts most and knows
        # least. `figures.py` had the same branch with the same hole and said
        # the file "parses" about a file that did not exist -- a pass on both
        # questions from the branch written to prevent one.
        #
        # With no file on disk there is nothing to fall back on, so `--record`
        # cannot keep its promise that the figures are current when it returns.
        if not target.exists():
            print("  figures/dag.html is MISSING and cannot be regenerated -- "
                  "the elaborated\n  export is not current, so the page cannot "
                  "be rebuilt. Refresh the\n  export, then re-run --record.")
            return 1
        print("NOTE: figures/dag.html was not checked -- the elaborated export "
              "is not\n      current, and refreshing it for a figure costs a "
              "rebuild of the tower.\n      The file on disk is unchanged and "
              "was NOT validated: this note is\n      about freshness only.")
        return 0
    # `--record` before a rebuild writes a figure asserting a count that was
    # true of the PREVIOUS tree, and only the gate catches it -- one cycle
    # later, after the wrong figure is committed. Foundations paid two cycles
    # for this and geometry hit it once; the `page() is None` NOTE above fires
    # only when the export is ABSENT, never when it is merely stale, which is
    # the case that costs anything.
    OUT.parent.mkdir(exist_ok=True)
    if args.record:
        OUT.write_text(fresh)
        print(f"  wrote figures/dag.html ({len(fresh) // 1024} KiB)")
        return 0
    if not OUT.exists():
        print("  figures/dag.html is missing -- run --record")
        return 1 if args.check else 0
    if OUT.read_text() != fresh:
        print("  figures/dag.html is stale -- the declarations or their")
        print("  dependencies moved. Run --record and commit it.")
        return 1 if args.check else 0
    print(f"  OK -- figures/dag.html matches the elaborated export "
          f"({len(fresh) // 1024} KiB drawn).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
